spring:
  datasource:
    url: jdbc:mysql://b5c3aecd47b363:7f044bdf@us-cdbr-iron-east-01.cleardb.net/heroku_3adcbb9d5624b60?reconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.gmail.com
    username: teste.trabalho093@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
          ssl:
            enable: true