server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql-monolito:3306/curso_spring
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    username: teste.trabalho093@gmail.com
    password: amoandroid
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
          ssl:
            enable: true