spring:
  profiles:
    active: test

default:
  sender: janainadepaula93@gmail.com
  recipient: janainadepaula93@gmail.com

jwt:
  secret: SequenciaDeCaracteresParaAssinarToken
  expiration: 86400000

aws:
  access_key_id: AKIAXOKQNQA4FB6D5YXX
  secret_access_key: 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
s3:
  bucket: ecommerce-monolito
  region: sa-east-1