server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    open-in-view: false