spring:
  profiles:
    active: test

default:
  sender: janainadepaula93@gmail.com
  recipient: janainadepaula93@gmail.com

jwt:
  secret: SequenciaDeCaracteresParaAssinarToken
  expiration: 86400000

aws:
  access_key_id:
  secret_access_key: 
s3:
  bucket: ecommerce-monolito
  region: sa-east-1