server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/curso_spring
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none